spring:
  application:
    name: GitHub OAuth Demo Application
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <client-secret-from-github-oauth-setup-step>
            client-secret: <client-secret-from-github-oauth-setup-step>
            redirect-uri: <redirect-uri-from-github-oauth-setup-step> # http://localhost:8080/login/oauth2/code/github
            scope: user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html